### ISSUE TITLE
Add compatibility for Shopware 6.6.x

### ISSUE THREAD

**Issue by baumisimon** [MultiSafepay/shopware6#13]
Shopware 6.6.0.0 was released on April 2nd 2024, the current version is 6.6.2.0.
Please update the plugin for 6.6.x, so we can update Shopware to the latest version.

**Comment by danielcivit** [comment]
Hello @baumisimon 

Thanks for your interest and request. 

I'm happy to announce that we just released a new version of our plugin (v 3.0.0) which provides support for Shopware 6.6.x.

I`m closing this ticket, but feel free to contact us or reopen this ticket if you have any other comments or questions.
