### ISSUE TITLE
Undefined property: stdClass::$amount_refunded, please check is exists before using it

### ISSUE THREAD

**Issue by StevendeVries** [MultiSafepay/shopware6#2]
The current code relies on a result always being properly filled, which is not always the case resulting in:

 `Uncaught PHP Exception ErrorException: "Notice: Undefined property: stdClass::$amount_refunded" at /var/www/vendor/multisafepay/shopware6/src/Storefront/Controller/RefundController.php line 90`

I would suggest checking if `amount_refunded` exists before using it and return 0 if it doesn't (just like line 87).

Here's the provided code lin
https://github.com/MultiSafepay/shopware6/blob/8b3fcc77bc7213bf084d02f78e3646f3c0cf646d/src/Storefront/Controller/RefundController.php#L90

**Comment by mikededecker1** [comment]
Hi Steven, We have added a check to our internal repository if the `amount_refunded` is available in the JSON request.

These changes will be available in the next release
