### ISSUE TITLE
You can't import directly from the Shopware core - Cannot build administration in Shopware 

### ISSUE THREAD

**Issue by janmartenjongerius** [MultiSafepay/shopware6#3]
The Shopware administration cannot be built because of a recent rule addition to their linting. See https://developer.shopware.com/docs/guides/plugins/plugins/administration/the-shopware-object

![image](https://user-images.githubusercontent.com/642417/136796977-1cd74146-757f-4eb4-98aa-ef71977ea939.png)

Affected Shopware version: `v6.4.5.1 Stable`

**Comment by janmartenjongerius** [comment]
@Jasper-MultiSafepay this is currently blocking a security update for Shopware. Would you be able to tell if this has the attention of MultiSafepay?

**Comment by Jasper-MultiSafepay** [comment]
@johmanx10 
It has, we'll have to check if it doesn't affect the older versions.
Will let you know as soon as we put out an update.

**Comment by janmartenjongerius** [comment]
Hey @Jasper-MultiSafepay and @Mike-MultiSafepay , do you have any update or timeline on this?

**Comment by Jasper-MultiSafepay** [comment]
@johmanx10 
This should already been released on the marketplace => https://store.shopware.com/en/mltis59465832976f/multisafepay-online-payments-for-shopware-ideal-cards-klarna-alipay-etc..html
I will chase internally to also update our repositories.

**Comment by janmartenjongerius** [comment]
@Jasper-MultiSafepay I can verify that this solves my problem. I'll close the issue.

Thanks so much for your and Mike's help!
