### ISSUE TITLE
Wrong locale in Multisafepay payment page

### ISSUE THREAD

**Issue by wallaceer** [MultiSafepay/shopware6#4]
The locale of Sales channel in Shopware is Italian, it isn't  English
https://testpayv2.multisafepay.com/connect/82OmWXdK7fMI83CadqbupYFIdGTbwiBrif6/?lang=en_GB
<img width="981" alt="Schermata 2021-10-15 alle 14 45 31" src="https://user-images.githubusercontent.com/881548/137490515-72849fe1-8f24-4557-9c84-92b5fce8ca6f.png">

The locale in payment url sent by shopware is always English (en_GB)

<img width="1485" alt="Schermata 2021-10-15 alle 14 58 41" src="https://user-images.githubusercontent.com/881548/137490617-3078610d-370c-4b7a-8804-17c202c639f0.png">

I don't see a configuration option in Multisafepay plugin.

Affected Shopware version: 6.4.4.0

**Comment by wallaceer** [comment]
Hi, are you not interesting it? :(

**Comment by Jasper-MultiSafepay** [comment]
@wallaceer 
We have fixed this internally. 
We will release an update to our plugin today.

**Comment by wallaceer** [comment]
Thanks @Jasper-MultiSafepay

**Comment by Jasper-MultiSafepay** [comment]
@wallaceer 
We have just released an update to our plugin.
It can be found at https://store.shopware.com/en/mltis59465832976f/multisafepay-online-payments-for-shopware-ideal-cards-klarna-alipay-etc..html

The issue with the locale should be fixed.
Please let us know if you experience any issues.
