### ISSUE TITLE
Vragen over transacties

### ISSUE THREAD

**Issue by khagele** [MultiSafepay/shopware6#9]
Van de Integration Specialist (mail id 81505) van MSP kreeg ik het verzoek of ik mijn vragen hier kon doorgeven.

Ik zie dat jullie plugin soms meerdere transacties per order registreert in Shopware. Voorbeeld uit de praktijk: 

Order:
.0 - open transactie
.1 - paid transactie
.2 - failed transactie

Als ik alleen naar de 1ste of laatste transactie kijken zie ik dus niet dat de order betaald is. Als ik zoek naar een paid transactie, kan ik dan de failed transactie negeren? 

Vragen: 
1. Als 1 van die transacties de status betaald heeft, dan kan de order 100% uitgeleverd worden? De status "paid" wordt dus onherroepelijk op een transactie gezet, en kan niet later worden aangepast? 

2. Er is geen deelbetaling mogelijk? Het kan dus niet zo zijn dat er een gedeelte wordt betaald, maar dat er toch de status paid op een transactie wordt gezet? 

3. Werkt dit voor alle MSP + Shopware gebruikers zo? Of is dit per MSP account instelbaar? 

4. Is er een plek waar ik de definitieve betaalstatus van een order in Shopware kan ophalen, of toch transacties bekijken op status? 

Hoor het graag, 

gr Kasper

**Comment by mikededecker1** [comment]
Hi @khagele 

We hebben gekeken naar uw vragen en zijn op het volgende punten gekomen.

>  Als 1 van die transacties de status betaald heeft, dan kan de order 100% uitgeleverd worden? De status "paid" wordt dus onherroepelijk op een transactie gezet, en kan niet later worden aangepast?

De order kan dan uitgeleverd worden. Het is wel dat de status aangepast kan worden naar 'refunded'. Maar deze status aanpassing word aangepast door de merchant, niet door MultiSafepay.

> Er is geen deelbetaling mogelijk? Het kan dus niet zo zijn dat er een gedeelte wordt betaald, maar dat er toch de status paid op een transactie wordt gezet?

Het is mogelijk om deelbatalingen te doen I.C.M. giftcard en een andere betaalmethode die geactiveerd staat binnen de MultiSafepay. Maar een order komt pas op 'completed' zodra deze helemaal is betaald.

> Werkt dit voor alle MSP + Shopware gebruikers zo? Of is dit per MSP account instelbaar?

Dit werkt voor alle MultiSafepay + Shopware gebruikers.

> Is er een plek waar ik de definitieve betaalstatus van een order in Shopware kan ophalen, of toch transacties bekijken op status?

Deze is alleen te vinden via de transactions endpoint van de order.

**Comment by khagele** [comment]
Dank je Mike. Hiermee kan ik verder. Twee sidequests wil ik je op wijzen, omdat die relevant kunnen zijn.

1. Whenever a payment method is changed, a new transaction in Shopware is created for the order.
Unfortunately the shopware administration panel can only show 1. and this is not the latest created one, but the last updated one. Here's the full story: https://issues.shopware.com/issues/NEXT-20338

2. In de code om de state van een transaction te wijzigen https://github.com/MultiSafepay/shopware6/blob/788a8fab58b2aa9a4e3b982668c6a5b970817171/src/Helper/CheckoutHelper.php#L70 vinden we $orderTransactionId, dat is interessant, omdat dit zegt over welke transactie het gaat. Die wordt alleen in NotificationController aangeroepen op regel [109](https://github.com/MultiSafepay/shopware6/blob/788a8fab58b2aa9a4e3b982668c6a5b970817171/src/Storefront/Controller/NotificationController.php#L109) en [152](https://github.com/MultiSafepay/shopware6/blob/788a8fab58b2aa9a4e3b982668c6a5b970817171/src/Storefront/Controller/NotificationController.php#L152). In die beide functies wordt de ordertransactie opgehaald door simpelweg de eerste op te halen: https://github.com/MultiSafepay/shopware6/blob/788a8fab58b2aa9a4e3b982668c6a5b970817171/src/Storefront/Controller/NotificationController.php#L100.

Misschien zijn er andere routes nog, maar misschien is er dus ook bij jullie de logica om alleen de eerste transactie te checken (net zoals aan onze kant, dat gaan we nu op basis van je antwoorden oplossen).
